# Generated by Django 3.1.3 on 2021-09-03 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('E', 'Entry-Level'), ('S', 'Senior-Level'), ('V', 'VP-Level')], max_length=30)),
                ('salary', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='job_list',
        ),
    ]
